// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxuwxbuokcksvqrssvte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4dXd4YnVva2Nrc3ZxcnNzdnRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MjEyMTQsImV4cCI6MjA4NjQ5NzIxNH0.v1Najdt3sRIdkA6bjr2ijDUerylAFYytds1iWnNeHds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});