// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxuwxbuokcksvqrssvte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4dXd4YnVva2Nrc3ZxcnNzdnRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MjEyMTQsImV4cCI6MjA4NjQ5NzIxNH0.v1Najdt3sRIdkA6bjr2ijDUerylAFYytds1iWnNeHds";

export const SUPABASE_ANON_KEY = SUPABASE_PUBLISHABLE_KEY;
export const SUPABASE_FUNCTIONS_URL = `${SUPABASE_URL}/functions/v1`;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Keep the functions client in sync with the current session token.
// By default, functions.invoke uses the anon key unless setAuth is called.
// The built-in listener only fires on SIGNED_IN / TOKEN_REFRESHED, not
// INITIAL_SESSION (restored from localStorage), so we sync it here.
supabase.auth.onAuthStateChange((_event, session) => {
  if (session?.access_token) {
    supabase.functions.setAuth(session.access_token);
  }
});